### PR TITLE
refactor to use fetch

### PR DESCRIPTION
**Pull request by dashed**

### CODE REVIEW

**Comment by thinkocapo** [comment]
thanks Alberto this works. I'll merge it, and then add back in sessionId and transactionId, as well as the `throw new Error(...)` at the end. I'll commit this on the apm-alpha branch.

I guess we could always put back `request` library if that gets supported one day. What do you think? @dashed

**Comment by dashed** [comment]
@thinkocapo yea that makes sense. Feel free to merge or recycle this change as you see fit.

There are other instances of `request` throughout the source code; it might be a good idea to refactor them in favour of `fetch`.

**Comment by thinkocapo** [comment]
if 'request is super common then I want to see if our team can issue an update to sentry/apm to fix this. We prefer to use whatever is most professional looking or expected, or performant as well.

if no resolution tomorrow then i'll go with Fetch for the time being. the fix could take a few days anyways so I might merge.

**Comment by thinkocapo** [comment]
teams decided that 'fetch is the way to go. merging.

**Pull request merged**
